### ISSUE TITLE
Bug - User is sometimes not redirected to the app after Google SignIn

### ISSUE THREAD

**Issue by ricardobrg** [tiki/strategy_google#85]
#### Description:
For unknown reasons, sometimes the google sign in web view results in the user not being returned to the app, and instead left viewing the web.

2FA may be related to this. This card is meant to find the exact cause/precise steps to reproduce.

#### Acceptance Criteria:
1. Known cause of this issue w/ steps to reproduce, and stories to fix

**Comment by NickkTMD** [comment]
this doesn't happen to me

**Comment by NickkTMD** [comment]
Original theory/cause:

If the user has 2FA enabled in the google account and never used the device to login in to Google, after the login it is redirected to the 2FA screen and back to the google home page, afterward.

#### Steps to Reproduce:
1. Use a gmail account with 2FA that was never used in the device.
2. Navigate to Data screen and login with Google.
3. Authenticate with password and 2FA
4. The app redirects to Google.com.

#### Expected behavior
After step 3, the user should be redirected back to the app, with google account connected.

**Comment by NickkTMD** [comment]
Can't get this to happen with updated login flow, closing for now as seems unimportant atm

**Comment by ricardobrg** [comment]
@NickkTMD did you try to reproduce this with the app? Maybe it just happens in the app, not in data lib...
